# Generated by Django 3.2 on 2021-05-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('email', models.CharField(blank=True, default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=250)),
                ('crazy', models.BooleanField(blank=True, default=False)),
                ('commentary', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('email', models.CharField(blank=True, default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=250)),
                ('message', models.TextField(default='')),
                ('date', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, default='', max_length=250)),
                ('main_image', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('date', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('payment', models.CharField(blank=True, default='', max_length=50)),
                ('commentary', models.TextField(blank=True, default='')),
                ('products', models.TextField(blank=True, default='')),
                ('total_price', models.IntegerField(blank=True, default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olegApi.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olegApi.product')),
            ],
        ),
    ]
